# Pre-commit hooks configuration
# See https://pre-commit.com for more information

repos:
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v3.6.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args:
          [
            "build",
            "chore",
            "ci",
            "docs",
            "feat",
            "fix",
            "perf",
            "style",
            "refactor",
            "test",
            "bump",
            "revert",
            "security",
          ]

  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.10.0.1
    hooks:
      - id: shellcheck
        name: ShellCheck
        args: ["-x", "--severity=warning"]
        types_or: [shell, bash]
        exclude: ^(\.git|\.vscode|docs|node_modules)/
        stages: [pre-commit, manual]

  - repo: https://github.com/scop/pre-commit-shfmt
    rev: v3.9.0-1
    hooks:
      - id: shfmt
        name: shfmt
        args: ["-i", "4", "-ci", "-sr", "-d"]
        types_or: [shell, bash]
        exclude: ^(\.git|\.vscode|docs|node_modules)/
        stages: [pre-commit, manual]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        name: Trim trailing whitespace
        exclude: ^(\.git|\.vscode)/
        stages: [pre-commit, manual]
      - id: end-of-file-fixer
        name: Fix end of files
        exclude: ^(\.git|\.vscode)/
        stages: [pre-commit, manual]
      - id: check-yaml
        name: Check YAML syntax
        exclude: ^(\.git|\.vscode)/
        stages: [pre-commit, manual]
      - id: check-added-large-files
        name: Check for large files
        args: ['--maxkb=500']
        stages: [pre-commit, manual]
      - id: check-case-conflict
        name: Check for case conflicts
        stages: [pre-commit, manual]
      - id: check-merge-conflict
        name: Check for merge conflicts
        stages: [pre-commit, manual]
      - id: mixed-line-ending
        name: Check mixed line endings
        args: ['--fix=lf']
        stages: [pre-commit, manual]
      - id: check-json
        name: Check JSON syntax
        exclude: ^(\.git|\.vscode)/
        stages: [pre-commit, manual]
